### PR TITLE
Added unlink executor

### PR DESCRIPTION
**Pull request by JohnGrisham**
Added unlink method

### CODE REVIEW

**Comment by xiongemi** [comment]
@JohnGrisham when would you need an unlink executor? what is the use case?

**Comment by JohnGrisham** [comment]
We have a monorepo where we were symlinking dependencies and it requires us to re clone the repo in order to do a direct install of node modules without the symlink.

**Comment by xiongemi** [comment]
@JohnGrisham I don't understand why could you need to clone the repo to install node modules. do your app node modules have different versions from workspace node modules?

**Comment by JohnGrisham** [comment]
Yes our app needs different versions than what is located at the root. There is a version conflict when symlinking.

**Comment by xiongemi** [comment]
thanks for submitting this pr. however, I think we are still going to use a single-version policy. ideally, expo app should have the same npm library version as the rest of the workspace.

**Pull request closed without merging**
