### PR TITLE
feat(expo): upgrade expo 45.0.4

### PR DESCRIPTION
**Pull request by xiongemi**

### CODE REVIEW

**Comment by vincentvella** [comment]
Does the CI just need to be re-run here? Gateway timeout downloading a dep?

**Comment by Deekor** [comment]
ETA on merging this? Waiting for it in a project of ours.

**Comment by xiongemi** [comment]
> ETA on merging this? Waiting for it in a project of ours.

it is now part of @nrwl/expo version 14.1.1. you should be able to upgrade it by running `nx migrate @nrwl/expo`

**Comment by vincentvella** [comment]
@xiongemi Ran the migration first thing this morning
Started receiving the following error:
```
> nx run keycustomer:run-ios

(0 , devkit_1.createProjectGraphAsync) is not a function

```

**Comment by xiongemi** [comment]
> @xiongemi Ran the migration first thing this morning Started receiving the following error:
> 
> ```
> > nx run <project-name>:run-ios
> 
> (0 , devkit_1.createProjectGraphAsync) is not a function
> ```

what version of @nrwl/devkit are you using? you might need to upgrade your @nrwl/devkit by running `nx migrate latest`.

**Comment by vincentvella** [comment]
That did it, thank you!

**Comment by vincentvella** [comment]
That worked, I had something pinning the devkit version to 13.8
Thanks!

**Pull request merged**
