### PR TITLE
feat(rspack): add module federation support

### PR DESCRIPTION
**Pull request by Coly010**
- feat(rspack): add withModuleFederation util
- feat(rspack): add module federation required executors
- feat(rspack): add module federation support

### CODE REVIEW

**Review by jaysoo — APPROVED** [review]

**Comment by jaysoo** [comment]
It looks like things are working, but I ran into two issues:

1. `webpack-dev-server@5.1.0` fails due to `TypeError: this.setupHostHeaderCheck is not a function`
2. Building the app results in a warning: `WARNING in ⚠ DefinePlugin:  │ Conflicting values for 'process.env.NODE_ENV' ("'production'" !== "\"production\"")`

**Comment by Coly010** [comment]
I've updated rspack deps to 1.0.2 which pins `webpack-dev-server@5.0.4` and I haven't been able to reproduce the definePlugin error

**Comment by VugarAhmadov** [comment]
Hi @Coly010. Thanks for the PR. will you add example repo for ModuleFederation and rspack?

**Comment by Coly010** [comment]
@VugarAhmadov There will be docs added soon :)

**Pull request merged**
